var obj = [
{Symbol:'WFC',Name:'Wells Fargo & Company',Price:24.17,Sector:'Finance',industry:'Major Banks'},
{Symbol:'HON',Name:'Honeywell International Inc.',Price:139.18,Sector:'Capital Goods',industry:'Aerospace'},
{Symbol:'BBL',Name:'BHP Group Plc',Price:37.91,Sector:'Energy',industry:'Coal Mining'},
{Symbol:'HSBC',Name:'HSBC Holdings plc',Price:22.97,Sector:'Finance',industry:'Savings Institutions'},
{Symbol:'TOT',Name:'Total S.A.',Price:36.02,Sector:'Energy',industry:'Oil & Gas Production'},
{Symbol:'LOW',Name:'Lowe&#39;s Companies, Inc.',Price:122.25,Sector:'Consumer Services',industry:'RETAIL: Building Materials'},
{Symbol:'C',Name:'Citigroup Inc.',Price:44.1,Sector:'Finance',industry:'Major Banks'},
{Symbol:'RTX',Name:'Raytheon Technologies Corporation',Price:60,Sector:'Capital Goods',industry:'Aerospace'},
{Symbol:'MMP',Name:'Magellan Midstream Partners L.P.',Price:44.36,Sector:'Energy',industry:'Natural Gas Distribution'},
{Symbol:'AYX',Name:'Alteryx, Inc.',Price:148.6,Sector:'Technology',industry:'Computer Software: Prepackaged Software'},
{Symbol:'DRI',Name:'Darden Restaurants, Inc.',Price:75.63,Sector:'Consumer Services',industry:'Restaurants'},
{Symbol:'QGEN',Name:'Qiagen N.V.',Price:42.99,Sector:'Health Care',industry:'Biotechnology: Biological Products (No Diagnostic Substances)'},
{Symbol:'KB',Name:'KB Financial Group Inc',Price:24.97,Sector:'Finance',industry:'Commercial Banks'},
{Symbol:'VST',Name:'Vistra Energy Corp.',Price:19.81,Sector:'Public Utilities',industry:'Electric Utilities: Central'},
{Symbol:'RF',Name:'Regions Financial Corporation',Price:9.95,Sector:'Finance',industry:'Major Banks'},
{Symbol:'URI',Name:'United Rentals, Inc.',Price:130.56,Sector:'Technology',industry:'Diversified Commercial Services'},
{Symbol:'DVA',Name:'DaVita Inc.',Price:76.81,Sector:'Health Care',industry:'Misc Health and Biotechnology Services'},
{Symbol:'ZEN',Name:'Zendesk, Inc.',Price:81.93,Sector:'Technology',industry:'EDP Services'},
{Symbol:'SUZ',Name:'Suzano S.A.',Price:6.92,Sector:'Basic Industries',industry:'Paper'},
{Symbol:'MPW',Name:'Medical Properties Trust, Inc.',Price:17.47,Sector:'Consumer Services',industry:'Real Estate Investment Trusts'},
{Symbol:'AAP',Name:'Advance Auto Parts Inc',Price:133.48,Sector:'Consumer Services',industry:'Other Specialty Stores'},
{Symbol:'MT',Name:'ArcelorMittal',Price:9.03,Sector:'Basic Industries',industry:'Steel/Iron Ore'},
{Symbol:'CFG',Name:'Citizens Financial Group, Inc.',Price:21.28,Sector:'Finance',industry:'Major Banks'},
{Symbol:'NLY',Name:'Annaly Capital Management Inc',Price:6.34,Sector:'Consumer Services',industry:'Real Estate Investment Trusts'},
{Symbol:'RPM',Name:'RPM International Inc.',Price:69.78,Sector:'Basic Industries',industry:'Paints/Coatings'},
{Symbol:'CDAY',Name:'Ceridian HCM Holding Inc.',Price:63.42,Sector:'Technology',industry:'Computer Software: Prepackaged Software'},
{Symbol:'RCL',Name:'Royal Caribbean Cruises Ltd.',Price:43.14,Sector:'Consumer Services',industry:'Marine Transportation'},
{Symbol:'BTI',Name:'British American Tobacco p.l.c.',Price:38.84,Sector:'Consumer Non-Durables',industry:'Farming/Seeds/Milling'},
{Symbol:'SHOP',Name:'Shopify Inc.',Price:825.17,Sector:'Technology',industry:'Computer Software: Prepackaged Software'},
{Symbol:'MMM',Name:'3M Company',Price:146.44,Sector:'Health Care',industry:'Medical/Dental Instruments'},
{Symbol:'FIS',Name:'Fidelity National Information Services, Inc.',Price:136.16,Sector:'Miscellaneous',industry:'Business Services'},
{Symbol:'RY',Name:'Royal Bank Of Canada',Price:58.87,Sector:'Finance',industry:'Commercial Banks'},
{Symbol:'UPS',Name:'United Parcel Service, Inc.',Price:96.72,Sector:'Transportation',industry:'Trucking Freight/Courier Services'},
{Symbol:'CVS',Name:'CVS Health Corporation',Price:63.33,Sector:'Health Care',industry:'Medical/Nursing Services'},
{Symbol:'DEO',Name:'Diageo plc',Price:138.67,Sector:'Consumer Non-Durables',industry:'Beverages (Production/Distribution)'},
{Symbol:'BUD',Name:'Anheuser-Busch Inbev SA',Price:40.9,Sector:'Consumer Non-Durables',industry:'Beverages (Production/Distribution)'},
{Symbol:'EMN',Name:'Eastman Chemical Company',Price:65.46,Sector:'Basic Industries',industry:'Major Chemicals'},
{Symbol:'L',Name:'Loews Corporation',Price:31.91,Sector:'Finance',industry:'Property-Casualty Insurers'},
{Symbol:'WPP',Name:'WPP plc',Price:36.53,Sector:'Technology',industry:'Advertising'},
{Symbol:'RJF',Name:'Raymond James Financial, Inc.',Price:65.21,Sector:'Finance',industry:'Investment Bankers/Brokers/Service'},
{Symbol:'PHM',Name:'PulteGroup, Inc.',Price:33.31,Sector:'Capital Goods',industry:'Homebuilding'},
{Symbol:'ATHM',Name:'Autohome Inc.',Price:74.5,Sector:'Technology',industry:'EDP Services'},
{Symbol:'AVY',Name:'Avery Dennison Corporation',Price:106.45,Sector:'Consumer Durables',industry:'Containers/Packaging'},
{Symbol:'BEN',Name:'Franklin Resources, Inc.',Price:17.89,Sector:'Finance',industry:'Investment Managers'},
{Symbol:'KGC',Name:'Kinross Gold Corporation',Price:7.05,Sector:'Basic Industries',industry:'Precious Metals'},
{Symbol:'UHS',Name:'Universal Health Services, Inc.',Price:104.17,Sector:'Health Care',industry:'Hospital/Nursing Management'},
{Symbol:'NI',Name:'NiSource, Inc',Price:23.09,Sector:'Public Utilities',industry:'Power Generation'},
{Symbol:'MGP',Name:'MGM Growth Properties LLC',Price:26.45,Sector:'Consumer Services',industry:'Real Estate Investment Trusts'},
{Symbol:'PKG',Name:'Packaging Corporation of America',Price:92.99,Sector:'Consumer Durables',industry:'Containers/Packaging'},
{Symbol:'VICI',Name:'VICI Properties Inc.',Price:18.83,Sector:'Consumer Services',industry:'Real Estate Investment Trusts'},
{Symbol:'ALLE',Name:'Allegion plc',Price:94.29,Sector:'Consumer Services',industry:'Diversified Commercial Services'},
{Symbol:'NRG',Name:'NRG Energy, Inc.',Price:35.72,Sector:'Public Utilities',industry:'Electric Utilities: Central'},
{Symbol:'BEP',Name:'Brookfield Renewable Partners L.P.',Price:48.5,Sector:'Public Utilities',industry:'Electric Utilities: Central'},
{Symbol:'CUK',Name:'Carnival Corporation',Price:12.19,Sector:'Consumer Services',industry:'Marine Transportation'},
{Symbol:'ASX',Name:'ASE Technology Holding Co., Ltd.',Price:4.06,Sector:'Technology',industry:'Semiconductors'},
{Symbol:'CPT',Name:'Camden Property Trust',Price:88.58,Sector:'Consumer Services',industry:'Real Estate Investment Trusts'},
{Symbol:'PAGS',Name:'PagSeguro Digital Ltd.',Price:26.3,Sector:'Technology',industry:'EDP Services'},
{Symbol:'CNP',Name:'CenterPoint Energy, Inc.',Price:16.92,Sector:'Public Utilities',industry:'Electric Utilities: Central'},
{Symbol:'CRL',Name:'Charles River Laboratories International, Inc.',Price:173.61,Sector:'Health Care',industry:'Biotechnology: Commercial Physical & Biological Resarch'},
{Symbol:'NET',Name:'Cloudflare, Inc.',Price:28.26,Sector:'Technology',industry:'Computer Software: Prepackaged Software'},
{Symbol:'RDY',Name:'Dr. Reddy&#39;s Laboratories Ltd',Price:51.41,Sector:'Health Care',industry:'Major Pharmaceuticals'},
{Symbol:'HUBS',Name:'HubSpot, Inc.',Price:194.29,Sector:'Technology',industry:'Computer Software: Prepackaged Software'},
{Symbol:'AVLR',Name:'Avalara, Inc.',Price:107.02,Sector:'Technology',industry:'Computer Software: Prepackaged Software'},
{Symbol:'BCH',Name:'Banco De Chile',Price:16.56,Sector:'Finance',industry:'Commercial Banks'},
{Symbol:'CCK',Name:'Crown Holdings, Inc.',Price:62.08,Sector:'Consumer Durables',industry:'Containers/Packaging'},
{Symbol:'GWRE',Name:'Guidewire Software, Inc.',Price:100.88,Sector:'Technology',industry:'Computer Software: Prepackaged Software'},
{Symbol:'LW',Name:'Lamb Weston Holdings, Inc.',Price:57.22,Sector:'Consumer Non-Durables',industry:'Packaged Foods'},
{Symbol:'SMG',Name:'Scotts Miracle-Gro Company (The)',Price:150.7,Sector:'Basic Industries',industry:'Agricultural Chemicals'},
{Symbol:'FBHS',Name:'Fortune Brands Home & Security, Inc.',Price:60.54,Sector:'Basic Industries',industry:'Homebuilding'},
{Symbol:'CCC',Name:'Clarivate Plc',Price:22.62,Sector:'Technology',industry:'EDP Services'},
{Symbol:'IHG',Name:'Intercontinental Hotels Group',Price:45.11,Sector:'Consumer Services',industry:'Hotels/Resorts'},
{Symbol:'RE',Name:'Everest Re Group, Ltd.',Price:205.68,Sector:'Finance',industry:'Property-Casualty Insurers'},
{Symbol:'PNW',Name:'Pinnacle West Capital Corporation',Price:72.66,Sector:'Public Utilities',industry:'Electric Utilities: Central'},
{Symbol:'AES',Name:'The AES Corporation',Price:12.24,Sector:'Basic Industries',industry:'Electric Utilities: Central'},
{Symbol:'CIEN',Name:'Ciena Corporation',Price:52.81,Sector:'Public Utilities',industry:'Telecommunications Equipment'},
{Symbol:'CNA',Name:'CNA Financial Corporation',Price:29.65,Sector:'Finance',industry:'Property-Casualty Insurers'},
{Symbol:'CHGG',Name:'Chegg, Inc.',Price:64.91,Sector:'Consumer Services',industry:'Other Consumer Services'},
{Symbol:'BLK',Name:'BlackRock, Inc.',Price:513.3,Sector:'Finance',industry:'Investment Bankers/Brokers/Service'},
{Symbol:'BA',Name:'Boeing Company (The)',Price:137.53,Sector:'Capital Goods',industry:'Aerospace'},
{Symbol:'BP',Name:'BP p.l.c.',Price:22.98,Sector:'Energy',industry:'Integrated oil Companies'},
{Symbol:'SNE',Name:'Sony Corp Ord',Price:63.24,Sector:'Consumer Non-Durables',industry:'Consumer Electronics/Appliances'},
{Symbol:'SPGI',Name:'S&P Global Inc.',Price:311.86,Sector:'Finance',industry:'Finance: Consumer Services'},
{Symbol:'NOW',Name:'ServiceNow, Inc.',Price:387.96,Sector:'Technology',industry:'Computer Software: Prepackaged Software'},
{Symbol:'AXP',Name:'American Express Company',Price:89.33,Sector:'Finance',industry:'Finance: Consumer Services'},
{Symbol:'TD',Name:'Toronto Dominion Bank (The)',Price:39.69,Sector:'Finance',industry:'Commercial Banks'},
{Symbol:'MO',Name:'Altria Group',Price:37.73,Sector:'Consumer Non-Durables',industry:'Farming/Seeds/Milling'},
{Symbol:'MBT',Name:'Mobile TeleSystems OJSC',Price:9.02,Sector:'Public Utilities',industry:'Telecommunications Equipment'},
{Symbol:'TAP',Name:'Molson Coors Beverage Company',Price:36.83,Sector:'Consumer Non-Durables',industry:'Beverages (Production/Distribution)'},
{Symbol:'EQH',Name:'Equitable Holdings, Inc.',Price:17.7,Sector:'Finance',industry:'Specialty Insurers'},
{Symbol:'HST',Name:'Host Hotels & Resorts, Inc.',Price:11.23,Sector:'Consumer Services',industry:'Real Estate Investment Trusts'},
{Symbol:'MTN',Name:'Vail Resorts, Inc.',Price:194.94,Sector:'Consumer Services',industry:'Services-Misc. Amusement & Recreation'},
{Symbol:'SJR',Name:'Shaw Communications Inc.',Price:15.98,Sector:'Consumer Services',industry:'Television Services'},
{Symbol:'MGM',Name:'MGM Resorts International',Price:15.9,Sector:'Consumer Services',industry:'Hotels/Resorts'},
{Symbol:'WU',Name:'Western Union Company (The)',Price:19.01,Sector:'Miscellaneous',industry:'Business Services'},
{Symbol:'GL',Name:'Globe Life Inc.',Price:72.54,Sector:'Finance',industry:'Life Insurance'},
{Symbol:'JNPR',Name:'Juniper Networks, Inc.',Price:23.16,Sector:'Technology',industry:'Computer Communications Equipment'},
{Symbol:'GGG',Name:'Graco Inc.',Price:45.87,Sector:'Capital Goods',industry:'Fluid Controls'},
{Symbol:'CNHI',Name:'CNH Industrial N.V.',Price:5.5,Sector:'Capital Goods',industry:'Construction/Ag Equipment/Trucks'},
{Symbol:'LII',Name:'Lennox International, Inc.',Price:198.43,Sector:'Capital Goods',industry:'Industrial Machinery/Components'},
{Symbol:'CHE',Name:'Chemed Corp.',Price:477.16,Sector:'Health Care',industry:'Medical/Nursing Services'},
{Symbol:'ELAN',Name:'Elanco Animal Health Incorporated',Price:18.94,Sector:'Health Care',industry:'Major Pharmaceuticals'},
{Symbol:'COG',Name:'Cabot Oil & Gas Corporation',Price:18.9,Sector:'Energy',industry:'Oil & Gas Production'},
{Symbol:'RNR',Name:'RenaissanceRe Holdings Ltd.',Price:170.97,Sector:'Finance',industry:'Property-Casualty Insurers'},
{Symbol:'HII',Name:'Huntington Ingalls Industries, Inc.',Price:182.77,Sector:'Capital Goods',industry:'Marine Transportation'},
{Symbol:'PRGO',Name:'Perrigo Company',Price:54.28,Sector:'Health Care',industry:'Major Pharmaceuticals'},
{Symbol:'BSAC',Name:'Banco Santander Chile',Price:15.9,Sector:'Finance',industry:'Commercial Banks'},
{Symbol:'FNF',Name:'Fidelity National Financial, Inc.',Price:27.45,Sector:'Finance',industry:'Specialty Insurers'},
{Symbol:'WHR',Name:'Whirlpool Corporation',Price:119.7,Sector:'Consumer Durables',industry:'Consumer Electronics/Appliances'},
{Symbol:'WUBA',Name:'58.com Inc.',Price:49.56,Sector:'Technology',industry:'Computer Software: Programming, Data Processing'},
{Symbol:'TREX',Name:'Trex Company, Inc.',Price:127.71,Sector:'Basic Industries',industry:'Forest Products'},
{Symbol:'AMH',Name:'American Homes 4 Rent',Price:24.18,Sector:'Consumer Services',industry:'Real Estate Investment Trusts'},
{Symbol:'EHC',Name:'Encompass Health Corporation',Price:73.17,Sector:'Health Care',industry:'Hospital/Nursing Management'},
{Symbol:'TS',Name:'Tenaris S.A.',Price:12.28,Sector:'Basic Industries',industry:'Steel/Iron Ore'},
{Symbol:'ALB',Name:'Albemarle Corporation',Price:68.11,Sector:'Basic Industries',industry:'Major Chemicals'},
{Symbol:'NTCO',Name:'Natura &Co Holding S.A.',Price:12.18,Sector:'n/a',industry:'n/a'},
{Symbol:'TTC',Name:'Toro Company (The)',Price:67.64,Sector:'Capital Goods',industry:'Tools/Hardware'},
{Symbol:'GSX',Name:'GSX Techedu Inc.',Price:29.73,Sector:'Consumer Services',industry:'Other Consumer Services'},
{Symbol:'PAA',Name:'Plains All American Pipeline, L.P.',Price:9.75,Sector:'Energy',industry:'Natural Gas Distribution'},
{Symbol:'EBR',Name:'Centrais Electricas Brasileiras S.A.- Eletrobras',Price:4.58,Sector:'Public Utilities',industry:'Electric Utilities: Central'},
{Symbol:'Y',Name:'Alleghany Corporation',Price:500.96,Sector:'Finance',industry:'Property-Casualty Insurers'},
{Symbol:'GNRC',Name:'Generac Holdlings Inc.',Price:114.4,Sector:'Consumer Durables',industry:'Metal Fabrications'},
{Symbol:'AQN',Name:'Algonquin Power & Utilities Corp.',Price:13.43,Sector:'Public Utilities',industry:'Electric Utilities: Central'},
{Symbol:'SNA',Name:'Snap-On Incorporated',Price:128.88,Sector:'Capital Goods',industry:'Industrial Machinery/Components'},
{Symbol:'WBC',Name:'Wabco Holdings Inc.',Price:136.37,Sector:'Capital Goods',industry:'Auto Manufacturing'},
{Symbol:'ANTM',Name:'Anthem, Inc.',Price:277.11,Sector:'Health Care',industry:'Medical Specialities'},
{Symbol:'CI',Name:'Cigna Corporation',Price:189,Sector:'Health Care',industry:'Medical Specialities'},
{Symbol:'SYK',Name:'Stryker Corporation',Price:184.14,Sector:'Health Care',industry:'Medical/Dental Instruments'},
{Symbol:'KOF',Name:'Coca Cola Femsa S.A.B. de C.V.',Price:40.28,Sector:'Consumer Non-Durables',industry:'Beverages (Production/Distribution)'},
{Symbol:'BDX',Name:'Becton, Dickinson and Company',Price:239.25,Sector:'Health Care',industry:'Medical/Dental Instruments'},
{Symbol:'D',Name:'Dominion Energy, Inc.',Price:80.51,Sector:'Public Utilities',industry:'Electric Utilities: Central'},
{Symbol:'HDB',Name:'HDFC Bank Limited',Price:36.72,Sector:'Finance',industry:'Commercial Banks'},
{Symbol:'CCI',Name:'Crown Castle International Corporation',Price:156.2,Sector:'Consumer Services',industry:'Real Estate Investment Trusts'},
{Symbol:'RIO',Name:'Rio Tinto Plc',Price:52.12,Sector:'Basic Industries',industry:'Precious Metals'},
{Symbol:'PLD',Name:'Prologis, Inc.',Price:87.55,Sector:'Consumer Services',industry:'Real Estate Investment Trusts'},
{Symbol:'BX',Name:'The Blackstone Group Inc.',Price:53.95,Sector:'Finance',industry:'Investment Managers'},
{Symbol:'EL',Name:'Estee Lauder Companies, Inc. (The)',Price:178.2,Sector:'Consumer Non-Durables',industry:'Package Goods/Cosmetics'},
{Symbol:'TJX',Name:'TJX Companies, Inc. (The)',Price:53.41,Sector:'Consumer Services',industry:'Clothing/Shoe/Accessory Stores'},
{Symbol:'ENB',Name:'Enbridge Inc',Price:31.47,Sector:'Energy',industry:'Natural Gas Distribution'},
{Symbol:'MS',Name:'Morgan Stanley',Price:40.13,Sector:'Finance',industry:'Investment Bankers/Brokers/Service'},
{Symbol:'GS',Name:'Goldman Sachs Group, Inc. (The)',Price:179.93,Sector:'Finance',industry:'Investment Bankers/Brokers/Service'},
{Symbol:'ZTS',Name:'Zoetis Inc.',Price:130.11,Sector:'Health Care',industry:'Major Pharmaceuticals'},
{Symbol:'DUK',Name:'Duke Energy Corporation',Price:83.23,Sector:'Public Utilities',industry:'Power Generation'},
{Symbol:'PTR',Name:'PetroChina Company Limited',Price:33.3,Sector:'Energy',industry:'Oil & Gas Production'},
{Symbol:'CAT',Name:'Caterpillar, Inc.',Price:112.47,Sector:'Capital Goods',industry:'Construction/Ag Equipment/Trucks'},
{Symbol:'CL',Name:'Colgate-Palmolive Company',Price:70.75,Sector:'Consumer Non-Durables',industry:'Package Goods/Cosmetics'},
{Symbol:'UBER',Name:'Uber Technologies, Inc.',Price:34.83,Sector:'Miscellaneous',industry:'Business Services'},
{Symbol:'PLAN',Name:'Anaplan, Inc.',Price:51.06,Sector:'Technology',industry:'Computer Software: Prepackaged Software'},
{Symbol:'GFI',Name:'Gold Fields Limited',Price:7.91,Sector:'Basic Industries',industry:'Precious Metals'},
{Symbol:'JHX',Name:'James Hardie Industries plc.',Price:15.76,Sector:'Capital Goods',industry:'Building Materials'},
{Symbol:'IRM',Name:'Iron Mountain Incorporated',Price:24.17,Sector:'Consumer Services',industry:'Real Estate Investment Trusts'},
{Symbol:'COLD',Name:'Americold Realty Trust',Price:34.69,Sector:'Consumer Services',industry:'Real Estate Investment Trusts'},
{Symbol:'AOS',Name:'A.O Smith Corporation',Price:42.22,Sector:'Consumer Durables',industry:'Consumer Electronics/Appliances'},
{Symbol:'XPO',Name:'XPO Logistics, Inc.',Price:75.61,Sector:'Consumer Services',industry:'Transportation Services'},
{Symbol:'SCI',Name:'Service Corporation International',Price:38.32,Sector:'Consumer Services',industry:'Other Consumer Services'},
{Symbol:'ESTC',Name:'Elastic N.V.',Price:83.47,Sector:'Technology',industry:'Computer Software: Prepackaged Software'},
{Symbol:'CGC',Name:'Canopy Growth Corporation',Price:19.42,Sector:'Consumer Durables',industry:'Specialty Chemicals'},
{Symbol:'KNX',Name:'Knight Transportation, Inc.',Price:39.9,Sector:'Transportation',industry:'Trucking Freight/Courier Services'},
{Symbol:'LNC',Name:'Lincoln National Corporation',Price:35,Sector:'Finance',industry:'Life Insurance'},
{Symbol:'ATR',Name:'AptarGroup, Inc.',Price:105.1,Sector:'Consumer Non-Durables',industry:'Plastic Products'},
{Symbol:'SMAR',Name:'Smartsheet Inc.',Price:56.56,Sector:'Technology',industry:'Computer Software: Prepackaged Software'},
{Symbol:'OHI',Name:'Omega Healthcare Investors, Inc.',Price:29.57,Sector:'Consumer Services',industry:'Real Estate Investment Trusts'},
{Symbol:'HRC',Name:'Hill-Rom Holdings Inc',Price:100.05,Sector:'Health Care',industry:'Medical/Dental Instruments'},
{Symbol:'WRK',Name:'Westrock Company',Price:25.35,Sector:'Consumer Durables',industry:'Containers/Packaging'},
{Symbol:'VNO',Name:'Vornado Realty Trust',Price:34.15,Sector:'Consumer Services',industry:'Real Estate Investment Trusts'},
{Symbol:'BFAM',Name:'Bright Horizons Family Solutions Inc.',Price:106.04,Sector:'Miscellaneous',industry:'Other Consumer Services'},
{Symbol:'G',Name:'Genpact Limited',Price:33.84,Sector:'Consumer Services',industry:'Professional Services'},
{Symbol:'IPG',Name:'Interpublic Group of Companies, Inc. (The)',Price:16.48,Sector:'Technology',industry:'Advertising'},
{Symbol:'NYT',Name:'New York Times Company (The)',Price:38.31,Sector:'Consumer Services',industry:'Newspapers/Magazines'},
{Symbol:'WSO',Name:'Watsco, Inc.',Price:165.73,Sector:'Consumer Durables',industry:'Industrial Machinery/Components'},
{Symbol:'SAM',Name:'Boston Beer Company, Inc. (The)',Price:520.19,Sector:'Consumer Non-Durables',industry:'Beverages (Production/Distribution)'},
{Symbol:'CSL',Name:'Carlisle Companies Incorporated',Price:115.38,Sector:'Basic Industries',industry:'Specialty Chemicals'},
{Symbol:'HUBB',Name:'Hubbell Inc',Price:116.86,Sector:'Capital Goods',industry:'Electrical Products'},
{Symbol:'UGI',Name:'UGI Corporation',Price:30.41,Sector:'Public Utilities',industry:'Natural Gas Distribution'},
{Symbol:'LEA',Name:'Lear Corporation',Price:105.4,Sector:'Capital Goods',industry:'Auto Parts:O.E.M.'},
{Symbol:'ARMK',Name:'Aramark',Price:24.56,Sector:'Consumer Services',industry:'Restaurants'},
{Symbol:'PCG',Name:'Pacific Gas & Electric Co.',Price:11.7,Sector:'Public Utilities',industry:'Power Generation'},
{Symbol:'BHC',Name:'Bausch Health Companies Inc.',Price:17.76,Sector:'Health Care',industry:'Major Pharmaceuticals'},
{Symbol:'KRC',Name:'Kilroy Realty Corporation',Price:54.26,Sector:'Consumer Services',industry:'Real Estate Investment Trusts'},
{Symbol:'PEN',Name:'Penumbra, Inc.',Price:176.99,Sector:'Health Care',industry:'Medical/Dental Instruments'},
{Symbol:'BWA',Name:'BorgWarner Inc.',Price:29.84,Sector:'Capital Goods',industry:'Auto Parts:O.E.M.'},
{Symbol:'OGE',Name:'OGE Energy Corp',Price:30.8,Sector:'Public Utilities',industry:'Electric Utilities: Central'},
{Symbol:'TXT',Name:'Textron Inc.',Price:26.91,Sector:'Capital Goods',industry:'Aerospace'},
{Symbol:'SQM',Name:'Sociedad Quimica y Minera S.A.',Price:23.22,Sector:'Basic Industries',industry:'Mining & Quarrying of Nonmetallic Minerals (No Fuels)'},
{Symbol:'CACI',Name:'CACI International, Inc.',Price:242.14,Sector:'Technology',industry:'EDP Services'},
{Symbol:'AIZ',Name:'Assurant, Inc.',Price:101.37,Sector:'Finance',industry:'Property-Casualty Insurers'},
{Symbol:'PNR',Name:'Pentair plc.',Price:36.48,Sector:'Technology',industry:'Industrial Machinery/Components'},
{Symbol:'WEX',Name:'WEX Inc.',Price:138.73,Sector:'Miscellaneous',industry:'Business Services'},
{Symbol:'AUY',Name:'Yamana Gold Inc.',Price:5.25,Sector:'Basic Industries',industry:'Precious Metals'},
{Symbol:'TAK',Name:'Takeda Pharmaceutical Company Limited',Price:18.93,Sector:'Health Care',industry:'Major Pharmaceuticals'},
{Symbol:'TGT',Name:'Target Corporation',Price:117.49,Sector:'Consumer Services',industry:'Department/Specialty Retail Stores'},
{Symbol:'CNI',Name:'Canadian National Railway Company',Price:82.44,Sector:'Transportation',industry:'Railroads'},
{Symbol:'ECL',Name:'Ecolab Inc.',Price:200.5,Sector:'Basic Industries',industry:'Package Goods/Cosmetics'},
{Symbol:'SO',Name:'Southern Company (The)',Price:54.58,Sector:'Public Utilities',industry:'Electric Utilities: Central'},
{Symbol:'VMW',Name:'Vmware, Inc.',Price:134.6,Sector:'Technology',industry:'Computer Software: Prepackaged Software'},
{Symbol:'GE',Name:'General Electric Company',Price:6.41,Sector:'Energy',industry:'Consumer Electronics/Appliances'},
{Symbol:'NOC',Name:'Northrop Grumman Corporation',Price:325.91,Sector:'Capital Goods',industry:'Industrial Machinery/Components'},
{Symbol:'BABA',Name:'Alibaba Group Holding Limited',Price:199.7,Sector:'Miscellaneous',industry:'Business Services'},
{Symbol:'SNP',Name:'China Petroleum & Chemical Corporation',Price:44.55,Sector:'Energy',industry:'Integrated oil Companies'},
{Symbol:'MMC',Name:'Marsh & McLennan Companies, Inc.',Price:104.5,Sector:'Finance',industry:'Specialty Insurers'},
{Symbol:'GPN',Name:'Global Payments Inc.',Price:176.75,Sector:'Miscellaneous',industry:'Business Services'},
{Symbol:'CB',Name:'Chubb Limited',Price:117,Sector:'Finance',industry:'Property-Casualty Insurers'},
{Symbol:'SHW',Name:'Sherwin-Williams Company (The)',Price:577.3,Sector:'Consumer Services',industry:'RETAIL: Building Materials'},
{Symbol:'HUM',Name:'Humana Inc.',Price:394.43,Sector:'Health Care',industry:'Medical Specialities'},
{Symbol:'APD',Name:'Air Products and Chemicals, Inc.',Price:234.35,Sector:'Basic Industries',industry:'Major Chemicals'},
{Symbol:'ITW',Name:'Illinois Tool Works Inc.',Price:163.75,Sector:'Technology',industry:'Industrial Machinery/Components'},
{Symbol:'ICE',Name:'Intercontinental Exchange Inc.',Price:93.77,Sector:'Finance',industry:'Investment Bankers/Brokers/Service'},
{Symbol:'LFC',Name:'China Life Insurance Company Limited',Price:9.07,Sector:'Finance',industry:'Life Insurance'},
{Symbol:'NEM',Name:'Newmont Corporation',Price:63.05,Sector:'Basic Industries',industry:'Precious Metals'},
{Symbol:'BSX',Name:'Boston Scientific Corporation',Price:35.91,Sector:'Health Care',industry:'Medical/Dental Instruments'},
{Symbol:'CF',Name:'CF Industries Holdings, Inc.',Price:27.59,Sector:'Basic Industries',industry:'Agricultural Chemicals'},
{Symbol:'FRT',Name:'Federal Realty Investment Trust',Price:78.49,Sector:'Consumer Services',industry:'Real Estate Investment Trusts'},
{Symbol:'ALLY',Name:'Ally Financial Inc.',Price:15.89,Sector:'Finance',industry:'Major Banks'},
{Symbol:'MHK',Name:'Mohawk Industries, Inc.',Price:83.31,Sector:'Consumer Durables',industry:'Home Furnishings'},
{Symbol:'DLB',Name:'Dolby Laboratories',Price:58.76,Sector:'Miscellaneous',industry:'Multi-Sector Companies'},
{Symbol:'VER',Name:'VEREIT Inc.',Price:5.45,Sector:'Consumer Services',industry:'Real Estate Investment Trusts'},
{Symbol:'HTA',Name:'Healthcare Trust of America, Inc.',Price:26.65,Sector:'Consumer Services',industry:'Real Estate Investment Trusts'},
{Symbol:'RS',Name:'Reliance Steel & Aluminum Co.',Price:91.46,Sector:'Basic Industries',industry:'Metal Fabrications'},
{Symbol:'POST',Name:'Post Holdings, Inc.',Price:84.84,Sector:'Consumer Non-Durables',industry:'Packaged Foods'},
{Symbol:'HLF',Name:'Herbalife Nutrition Ltd.',Price:41.65,Sector:'Health Care',industry:'Other Pharmaceuticals'},
{Symbol:'ACM',Name:'AECOM',Price:35.82,Sector:'Consumer Services',industry:'Military/Government/Technical'},
{Symbol:'DCI',Name:'Donaldson Company, Inc.',Price:45.12,Sector:'Capital Goods',industry:'Pollution Control Equipment'},
{Symbol:'IPHI',Name:'Inphi Corporation',Price:118.37,Sector:'Technology',industry:'Semiconductors'},
{Symbol:'HNP',Name:'Huaneng Power International, Inc.',Price:14.4,Sector:'Public Utilities',industry:'Electric Utilities: Central'},
{Symbol:'SWI',Name:'SolarWinds Corporation',Price:18.04,Sector:'Technology',industry:'Computer Software: Prepackaged Software'},
{Symbol:'PB',Name:'Prosperity Bancshares, Inc.',Price:60.62,Sector:'Finance',industry:'Major Banks'},
{Symbol:'WLK',Name:'Westlake Chemical Corporation',Price:44.01,Sector:'Basic Industries',industry:'Major Chemicals'},
{Symbol:'ALV',Name:'Autoliv, Inc.',Price:63.95,Sector:'Capital Goods',industry:'Auto Parts:O.E.M.'},
{Symbol:'GFL',Name:'GFL Environmental Inc.',Price:17.69,Sector:'Public Utilities',industry:'Environmental Services'},
{Symbol:'RGA',Name:'Reinsurance Group of America, Incorporated',Price:90,Sector:'Finance',industry:'Life Insurance'},
{Symbol:'CIB',Name:'BanColombia S.A.',Price:23.06,Sector:'Finance',industry:'Commercial Banks'},
{Symbol:'TSU',Name:'TIM Participacoes S.A.',Price:11.43,Sector:'Public Utilities',industry:'Telecommunications Equipment'},
{Symbol:'FAF',Name:'First American Corporation (The)',Price:49.47,Sector:'Finance',industry:'Specialty Insurers'},
{Symbol:'BERY',Name:'Berry Global Group, Inc.',Price:40.72,Sector:'Consumer Non-Durables',industry:'Plastic Products'},
{Symbol:'HESM',Name:'Hess Midstream LP',Price:19.29,Sector:'Energy',industry:'Oil & Gas Production'},
{Symbol:'ST',Name:'Sensata Technologies Holding plc',Price:34.95,Sector:'Capital Goods',industry:'Industrial Machinery/Components'},
{Symbol:'CEA',Name:'China Eastern Airlines Corporation Ltd.',Price:16.72,Sector:'Transportation',industry:'Air Freight/Delivery Services'},
{Symbol:'HAE',Name:'Haemonetics Corporation',Price:108.14,Sector:'Health Care',industry:'Medical/Dental Instruments'},
{Symbol:'PLNT',Name:'Planet Fitness, Inc.',Price:62.96,Sector:'Consumer Services',industry:'Hotels/Resorts'},
{Symbol:'BWXT',Name:'BWX Technologies, Inc.',Price:57.05,Sector:'Energy',industry:'Industrial Machinery/Components'},
{Symbol:'RHI',Name:'Robert Half International Inc.',Price:47.41,Sector:'Technology',industry:'Professional Services'},
{Symbol:'HWM',Name:'Howmet Aerospace Inc.',Price:12.37,Sector:'Capital Goods',industry:'Metal Fabrications'},
{Symbol:'UMC',Name:'United Microelectronics Corporation',Price:2.46,Sector:'Technology',industry:'Semiconductors'},
{Symbol:'AFG',Name:'American Financial Group, Inc.',Price:59.81,Sector:'Finance',industry:'Property-Casualty Insurers'},
{Symbol:'ZNH',Name:'China Southern Airlines Company Limited',Price:20.86,Sector:'Transportation',industry:'Air Freight/Delivery Services'},
{Symbol:'GMED',Name:'Globus Medical, Inc.',Price:55.11,Sector:'Health Care',industry:'Medical/Dental Instruments'},
{Symbol:'RL',Name:'Ralph Lauren Corporation',Price:72.84,Sector:'Consumer Non-Durables',industry:'Apparel'},
{Symbol:'SBS',Name:'Companhia de saneamento Basico Do Estado De Sao Paulo - Sabesp',Price:7.82,Sector:'Public Utilities',industry:'Water Supply'},
{Symbol:'AIV',Name:'Apartment Investment and Management Company',Price:35.9,Sector:'Consumer Services',industry:'Real Estate Investment Trusts'},
{Symbol:'H',Name:'Hyatt Hotels Corporation',Price:52.74,Sector:'Consumer Services',industry:'Hotels/Resorts'},
{Symbol:'INGR',Name:'Ingredion Incorporated',Price:79.54,Sector:'Consumer Non-Durables',industry:'Packaged Foods'},
{Symbol:'NNN',Name:'National Retail Properties',Price:30.89,Sector:'Consumer Services',industry:'Real Estate Investment Trusts'},
{Symbol:'VOYA',Name:'Voya Financial, Inc.',Price:42.09,Sector:'Finance',industry:'Life Insurance'},
{Symbol:'OCFT',Name:'OneConnect Financial Technology Co., Ltd.',Price:14.07,Sector:'Technology',industry:'Computer Software: Programming, Data Processing'},
{Symbol:'GRUB',Name:'GrubHub Inc.',Price:57.35,Sector:'Miscellaneous',industry:'Business Services'},
{Symbol:'SBSW',Name:'Sibayne Gold Limited',Price:7.88,Sector:'n/a',industry:'n/a'},
{Symbol:'SHLX',Name:'Shell Midstream Partners, L.P.',Price:13.36,Sector:'Energy',industry:'Natural Gas Distribution'},
{Symbol:'ARW',Name:'Arrow Electronics, Inc.',Price:66.51,Sector:'Technology',industry:'Electronic Components'},
{Symbol:'CVE',Name:'Cenovus Energy Inc',Price:4.25,Sector:'Energy',industry:'Oil & Gas Production'},
{Symbol:'OC',Name:'Owens Corning Inc',Price:48.43,Sector:'Capital Goods',industry:'Industrial Machinery/Components'},
{Symbol:'PHI',Name:'PLDT Inc.',Price:23.96,Sector:'Public Utilities',industry:'Telecommunications Equipment'},
{Symbol:'SNX',Name:'Synnex Corporation',Price:100.59,Sector:'Technology',industry:'Retail: Computer Software & Peripheral Equipment'},
{Symbol:'BJ',Name:'BJ&#39;s Wholesale Club Holdings, Inc.',Price:37.09,Sector:'Consumer Services',industry:'Department/Specialty Retail Stores'},
{Symbol:'CLR',Name:'Continental Resources, Inc.',Price:14.04,Sector:'Energy',industry:'Oil & Gas Production'},
{Symbol:'PII',Name:'Polaris Inc.',Price:83.72,Sector:'Capital Goods',industry:'Industrial Specialties'},
{Symbol:'WSM',Name:'Williams-Sonoma, Inc.',Price:66.49,Sector:'Consumer Services',industry:'Home Furnishings'},
{Symbol:'LEVI',Name:'Levi Strauss & Co',Price:12.92,Sector:'Consumer Non-Durables',industry:'Apparel'},
{Symbol:'FND',Name:'Floor & Decor Holdings, Inc.',Price:49.79,Sector:'Consumer Services',industry:'RETAIL: Building Materials'},
{Symbol:'GLOB',Name:'Globant S.A.',Price:137,Sector:'Technology',industry:'EDP Services'},
{Symbol:'AXTA',Name:'Axalta Coating Systems Ltd.',Price:21.54,Sector:'Basic Industries',industry:'Paints/Coatings'},
{Symbol:'AEG',Name:'Aegon NV',Price:2.46,Sector:'Finance',industry:'Life Insurance'},
{Symbol:'ATH',Name:'Athene Holding Ltd.',Price:26,Sector:'Finance',industry:'Life Insurance'},
{Symbol:'BG',Name:'Bunge Limited',Price:35.38,Sector:'Consumer Non-Durables',industry:'Packaged Foods'},
{Symbol:'ADT',Name:'ADT Inc.',Price:6.52,Sector:'Consumer Services',industry:'Diversified Commercial Services'},
{Symbol:'DECK',Name:'Deckers Outdoor Corporation',Price:179.24,Sector:'Consumer Non-Durables',industry:'Shoe Manufacturing'},
{Symbol:'ENIC',Name:'Enel Chile S.A.',Price:3.63,Sector:'Public Utilities',industry:'Electric Utilities: Central'},
{Symbol:'USB',Name:'U.S. Bancorp',Price:32.93,Sector:'Finance',industry:'Major Banks'},
{Symbol:'MUFG',Name:'Mitsubishi UFJ Financial Group Inc',Price:3.86,Sector:'Finance',industry:'Commercial Banks'},
{Symbol:'EQNR',Name:'Equinor ASA',Price:14.78,Sector:'Energy',industry:'Integrated oil Companies'},
{Symbol:'MCO',Name:'Moody&#39;s Corporation',Price:256.82,Sector:'Finance',industry:'Finance: Consumer Services'},
{Symbol:'BAM',Name:'Brookfield Asset Management Inc',Price:30.3,Sector:'Consumer Services',industry:'Building operators'},
{Symbol:'KMB',Name:'Kimberly-Clark Corporation',Price:139.74,Sector:'Consumer Durables',industry:'Containers/Packaging'},
{Symbol:'GOLD',Name:'Barrick Gold Corporation',Price:26.32,Sector:'Basic Industries',industry:'Precious Metals'},
{Symbol:'COP',Name:'ConocoPhillips',Price:43.28,Sector:'Energy',industry:'Integrated oil Companies'},
{Symbol:'EW',Name:'Edwards Lifesciences Corporation',Price:218.81,Sector:'Health Care',industry:'Industrial Specialties'},
{Symbol:'VALE',Name:'VALE S.A.',Price:8.98,Sector:'Basic Industries',industry:'Precious Metals'},
{Symbol:'PBR',Name:'Petroleo Brasileiro S.A.- Petrobras',Price:7.06,Sector:'Energy',industry:'Oil & Gas Production'},
{Symbol:'DG',Name:'Dollar General Corporation',Price:178.98,Sector:'Consumer Services',industry:'Department/Specialty Retail Stores'},
{Symbol:'TFC',Name:'Truist Financial Corporation',Price:33.29,Sector:'Finance',industry:'Major Banks'},
{Symbol:'PNC',Name:'PNC Financial Services Group, Inc. (The)',Price:104.61,Sector:'Finance',industry:'Major Banks'},
{Symbol:'AON',Name:'Aon plc',Price:191.97,Sector:'Finance',industry:'Specialty Insurers'},
{Symbol:'RELX',Name:'RELX PLC',Price:22.97,Sector:'Consumer Services',industry:'Publishing'},
{Symbol:'BNS',Name:'Bank of Nova Scotia (The)',Price:36.54,Sector:'Finance',industry:'Major Banks'},
{Symbol:'BAX',Name:'Baxter International Inc.',Price:86.93,Sector:'Health Care',industry:'Medical/Dental Instruments'},
{Symbol:'DE',Name:'Deere & Company',Price:140.71,Sector:'Capital Goods',industry:'Industrial Machinery/Components'},
{Symbol:'NSC',Name:'Norfolk Southern Corporation',Price:171.47,Sector:'Transportation',industry:'Railroads'},
{Symbol:'PGR',Name:'Progressive Corporation (The)',Price:74.72,Sector:'Finance',industry:'Property-Casualty Insurers'},
{Symbol:'SCHW',Name:'The Charles Schwab Corporation',Price:32.83,Sector:'Finance',industry:'Investment Bankers/Brokers/Service'},
{Symbol:'AMX',Name:'America Movil, S.A.B. de C.V.',Price:12.8,Sector:'Public Utilities',industry:'Telecommunications Equipment'},
{Symbol:'WM',Name:'Waste Management, Inc.',Price:98.92,Sector:'Public Utilities',industry:'Environmental Services'},
{Symbol:'AMOV',Name:'America Movil, S.A.B. de C.V.',Price:12.5501,Sector:'Public Utilities',industry:'Telecommunications Equipment'},
{Symbol:'V',Name:'Visa Inc.',Price:190.86,Sector:'Miscellaneous',industry:'Business Services'},
{Symbol:'EPD',Name:'Enterprise Products Partners L.P.',Price:18.68,Sector:'Public Utilities',industry:'Natural Gas Distribution'},
{Symbol:'HMC',Name:'Honda Motor Company, Ltd.',Price:23.61,Sector:'Capital Goods',industry:'Auto Manufacturing'},
{Symbol:'ABB',Name:'ABB Ltd',Price:18.77,Sector:'Consumer Durables',industry:'Electrical Products'},
{Symbol:'KIM',Name:'Kimco Realty Corporation',Price:11.33,Sector:'Consumer Services',industry:'Real Estate Investment Trusts'},
{Symbol:'SC',Name:'Santander Consumer USA Holdings Inc.',Price:15.47,Sector:'Finance',industry:'Finance: Consumer Services'},
{Symbol:'IAA',Name:'IAA, Inc.',Price:37.06,Sector:'Consumer Durables',industry:'Automotive Aftermarket'},
{Symbol:'CUBE',Name:'CubeSmart',Price:25.54,Sector:'Consumer Services',industry:'Real Estate Investment Trusts'},
{Symbol:'HFC',Name:'HollyFrontier Corporation',Price:30.46,Sector:'Energy',industry:'Integrated oil Companies'},
{Symbol:'SON',Name:'Sonoco Products Company',Price:49.14,Sector:'Consumer Durables',industry:'Containers/Packaging'},
{Symbol:'SAIC',Name:'SCIENCE APPLICATIONS INTERNATIONAL CORPORATION',Price:84.91,Sector:'Technology',industry:'EDP Services'},
{Symbol:'KT',Name:'KT Corporation',Price:9.78,Sector:'Public Utilities',industry:'Telecommunications Equipment'},
{Symbol:'DEI',Name:'Douglas Emmett, Inc.',Price:27.72,Sector:'Consumer Services',industry:'Real Estate Investment Trusts'},
{Symbol:'FLO',Name:'Flowers Foods, Inc.',Price:22.89,Sector:'Consumer Non-Durables',industry:'Packaged Foods'},
{Symbol:'NLSN',Name:'Nielsen N.V.',Price:13.59,Sector:'Miscellaneous',industry:'Business Services'},
{Symbol:'BILL',Name:'Bill.com Holdings, Inc.',Price:66.57,Sector:'Technology',industry:'Computer Software: Prepackaged Software'},
{Symbol:'JLL',Name:'Jones Lang LaSalle Incorporated',Price:93.57,Sector:'Finance',industry:'Real Estate'},
{Symbol:'ORCC',Name:'Owl Rock Capital Corporation',Price:12.56,Sector:'n/a',industry:'n/a'},
{Symbol:'TECK',Name:'Teck Resources Ltd',Price:9.16,Sector:'Basic Industries',industry:'Mining & Quarrying of Nonmetallic Minerals (No Fuels)'},
{Symbol:'REXR',Name:'Rexford Industrial Realty, Inc.',Price:38.77,Sector:'Consumer Services',industry:'Real Estate Investment Trusts'},
{Symbol:'NEU',Name:'NewMarket Corporation',Price:434.54,Sector:'Basic Industries',industry:'Major Chemicals'},
{Symbol:'FTCH',Name:'Farfetch Limited',Price:13.85,Sector:'Miscellaneous',industry:'Business Services'},
{Symbol:'PWR',Name:'Quanta Services, Inc.',Price:34.25,Sector:'Capital Goods',industry:'Engineering & Construction'},
{Symbol:'SWCH',Name:'Switch, Inc.',Price:19.02,Sector:'Technology',industry:'Computer Software: Programming, Data Processing'},
{Symbol:'WF',Name:'Woori Bank',Price:19.09,Sector:'Finance',industry:'Commercial Banks'},
{Symbol:'NOV',Name:'National Oilwell Varco, Inc.',Price:12.09,Sector:'Energy',industry:'Metal Fabrications'},
{Symbol:'ITT',Name:'ITT Inc.',Price:54.26,Sector:'Capital Goods',industry:'Fluid Controls'},
{Symbol:'DVN',Name:'Devon Energy Corporation',Price:12.14,Sector:'Energy',industry:'Oil & Gas Production'},
{Symbol:'MRO',Name:'Marathon Oil Corporation',Price:5.89,Sector:'Energy',industry:'Oil & Gas Production'},
{Symbol:'ARES',Name:'Ares Management Corporation',Price:35.06,Sector:'Finance',industry:'Investment Managers'},
{Symbol:'SEE',Name:'Sealed Air Corporation',Price:29.8,Sector:'Basic Industries',industry:'Major Chemicals'},
{Symbol:'COR',Name:'CoreSite Realty Corporation',Price:122,Sector:'Consumer Services',industry:'Real Estate Investment Trusts'},
{Symbol:'SKX',Name:'Skechers U.S.A., Inc.',Price:29.27,Sector:'Consumer Non-Durables',industry:'Shoe Manufacturing'},
{Symbol:'FR',Name:'First Industrial Realty Trust, Inc.',Price:36.26,Sector:'Consumer Services',industry:'Real Estate Investment Trusts'},
{Symbol:'APA',Name:'Apache Corporation',Price:12.17,Sector:'Energy',industry:'Oil & Gas Production'},
{Symbol:'STOR',Name:'STORE Capital Corporation',Price:18.72,Sector:'Consumer Services',industry:'Real Estate Investment Trusts'},
{Symbol:'CMA',Name:'Comerica Incorporated',Price:32.65,Sector:'Finance',industry:'Major Banks'},
{Symbol:'ORI',Name:'Old Republic International Corporation',Price:14.92,Sector:'Finance',industry:'Property-Casualty Insurers'},
{Symbol:'AVAL',Name:'Grupo Aval Acciones y Valores S.A.',Price:4.07,Sector:'Finance',industry:'Commercial Banks'},
{Symbol:'MSA',Name:'MSA Safety Incorporporated',Price:116.39,Sector:'Health Care',industry:'Industrial Specialties'},
{Symbol:'THO',Name:'Thor Industries, Inc.',Price:81.94,Sector:'Consumer Non-Durables',industry:'Homebuilding'},
{Symbol:'NVRO',Name:'Nevro Corp.',Price:129.51,Sector:'Health Care',industry:'Medical/Dental Instruments'},
{Symbol:'OSK',Name:'Oshkosh Corporation',Price:65.66,Sector:'Capital Goods',industry:'Auto Manufacturing'},
{Symbol:'TPL',Name:'Texas Pacific Land Trust',Price:576.12,Sector:'Energy',industry:'Oil & Gas Production'},
{Symbol:'IDA',Name:'IDACORP, Inc.',Price:88.1,Sector:'Public Utilities',industry:'Electric Utilities: Central'},
{Symbol:'EBS',Name:'Emergent Biosolutions, Inc.',Price:84.59,Sector:'Health Care',industry:'Major Pharmaceuticals'},
{Symbol:'TKC',Name:'Turkcell Iletisim Hizmetleri AS',Price:5.06,Sector:'Public Utilities',industry:'Telecommunications Equipment'},
{Symbol:'MMS',Name:'Maximus, Inc.',Price:70.16,Sector:'Miscellaneous',industry:'Business Services'},
{Symbol:'JBL',Name:'Jabil Inc.',Price:29.11,Sector:'Technology',industry:'Electrical Products'},
{Symbol:'LM',Name:'Legg Mason, Inc.',Price:49.8,Sector:'Finance',industry:'Investment Managers'},
{Symbol:'MOS',Name:'Mosaic Company (The)',Price:11.56,Sector:'Basic Industries',industry:'Agricultural Chemicals'},
{Symbol:'ICL',Name:'ICL Group Ltd.',Price:3.41,Sector:'Basic Industries',industry:'Agricultural Chemicals'},
{Symbol:'WH',Name:'Wyndham Hotels & Resorts, Inc.',Price:46.97,Sector:'Consumer Services',industry:'Hotels/Resorts'},
{Symbol:'VEDL',Name:'Vedanta  Limited',Price:4.69,Sector:'Capital Goods',industry:'Metal Fabrications'},
{Symbol:'PRI',Name:'Primerica, Inc.',Price:108.33,Sector:'Finance',industry:'Life Insurance'},
{Symbol:'QTWO',Name:'Q2 Holdings, Inc.',Price:81.84,Sector:'Technology',industry:'Computer Software: Prepackaged Software'},
{Symbol:'CHH',Name:'Choice Hotels International, Inc.',Price:78.39,Sector:'Consumer Services',industry:'Hotels/Resorts'},
{Symbol:'ACC',Name:'American Campus Communities Inc',Price:31.45,Sector:'Consumer Services',industry:'Real Estate Investment Trusts'},
{Symbol:'RBA',Name:'Ritchie Bros. Auctioneers Incorporated',Price:39.99,Sector:'Miscellaneous',industry:'Business Services'},
{Symbol:'SLQT',Name:'SelectQuote, Inc.',Price:26.5,Sector:'n/a',industry:'n/a'},
{Symbol:'CFR',Name:'Cullen/Frost Bankers, Inc.',Price:68.55,Sector:'Finance',industry:'Major Banks'},
{Symbol:'PSTG',Name:'Pure Storage, Inc. ',Price:16.27,Sector:'Technology',industry:'Electronic Components'},
{Symbol:'FCN',Name:'FTI Consulting, Inc.',Price:115.4,Sector:'Consumer Services',industry:'Professional Services'},
{Symbol:'NOMD',Name:'Nomad Foods Limited',Price:21.28,Sector:'Consumer Non-Durables',industry:'Packaged Foods'},
{Symbol:'EGP',Name:'EastGroup Properties, Inc.',Price:109.23,Sector:'Consumer Services',industry:'Real Estate Investment Trusts'},
{Symbol:'MDU',Name:'MDU Resources Group, Inc.',Price:21.15,Sector:'Basic Industries',industry:'Mining & Quarrying of Nonmetallic Minerals (No Fuels)'},
{Symbol:'PSO',Name:'Pearson, Plc',Price:5.62,Sector:'Consumer Services',industry:'Books'},
{Symbol:'CWEN',Name:'Clearway Energy, Inc.',Price:21.16,Sector:'Public Utilities',industry:'Electric Utilities: Central'},
{Symbol:'BC',Name:'Brunswick Corporation',Price:53.19,Sector:'Energy',industry:'Industrial Machinery/Components'},
{Symbol:'LSI',Name:'Life Storage, Inc.',Price:89.85,Sector:'Consumer Services',industry:'Real Estate Investment Trusts'},
{Symbol:'NYCB',Name:'New York Community Bancorp, Inc.',Price:9.07,Sector:'Finance',industry:'Banks'},
{Symbol:'TRGP',Name:'Targa Resources, Inc.',Price:18.04,Sector:'Public Utilities',industry:'Natural Gas Distribution'},
{Symbol:'MAN',Name:'ManpowerGroup',Price:70.66,Sector:'Technology',industry:'Professional Services'},
{Symbol:'LB',Name:'L Brands, Inc.',Price:15.08,Sector:'Consumer Services',industry:'Clothing/Shoe/Accessory Stores'},
{Symbol:'OGS',Name:'ONE Gas, Inc.',Price:78.54,Sector:'Public Utilities',industry:'Oil/Gas Transmission'},
{Symbol:'EV',Name:'Eaton Vance Corporation',Price:35.91,Sector:'Finance',industry:'Investment Managers'},
{Symbol:'HR',Name:'Healthcare Realty Trust Incorporated',Price:30.47,Sector:'Consumer Services',industry:'Real Estate Investment Trusts'},
{Symbol:'HE',Name:'Hawaiian Electric Industries, Inc.',Price:37.27,Sector:'Public Utilities',industry:'Electric Utilities: Central'},
{Symbol:'KMPR',Name:'Kemper Corporation',Price:62.43,Sector:'Finance',industry:'Property-Casualty Insurers'},
{Symbol:'SITE',Name:'SiteOne Landscape Supply, Inc.',Price:97,Sector:'Consumer Non-Durables',industry:'Farming/Seeds/Milling'},
{Symbol:'ALSN',Name:'Allison Transmission Holdings, Inc.',Price:35.71,Sector:'Capital Goods',industry:'Auto Parts:O.E.M.'},
{Symbol:'SWX',Name:'Southwest Gas Holdings, Inc.',Price:73.37,Sector:'Public Utilities',industry:'Oil & Gas Production'},
{Symbol:'CUZ',Name:'Cousins Properties Incorporated',Price:27.16,Sector:'Consumer Services',industry:'Real Estate Investment Trusts'},
{Symbol:'MSGS',Name:'Madison Square Garden Sports Corp.',Price:166.94,Sector:'Consumer Services',industry:'Services-Misc. Amusement & Recreation'},
{Symbol:'PHG',Name:'Koninklijke Philips N.V.',Price:44.52,Sector:'Energy',industry:'Consumer Electronics/Appliances'},
{Symbol:'ITUB',Name:'Itau Unibanco Banco Holding SA',Price:4.08,Sector:'Finance',industry:'Major Banks'},
{Symbol:'RACE',Name:'Ferrari N.V.',Price:160.48,Sector:'Capital Goods',industry:'Auto Manufacturing'},
{Symbol:'GD',Name:'General Dynamics Corporation',Price:138.57,Sector:'Capital Goods',industry:'Marine Transportation'},
{Symbol:'TRP',Name:'TC Energy Corporation',Price:42.11,Sector:'Public Utilities',industry:'Natural Gas Distribution'},
{Symbol:'AEP',Name:'American Electric Power Company, Inc.',Price:78.78,Sector:'Public Utilities',industry:'Electric Utilities: Central'},
{Symbol:'JNJ',Name:'Johnson & Johnson',Price:144.37,Sector:'Health Care',industry:'Major Pharmaceuticals'},
{Symbol:'LHX',Name:'L3Harris Technologies, Inc.',Price:180.45,Sector:'Capital Goods',industry:'Industrial Machinery/Components'},
{Symbol:'INFY',Name:'Infosys Limited',Price:9.05,Sector:'Technology',industry:'EDP Services'},
{Symbol:'ROP',Name:'Roper Technologies, Inc.',Price:367.06,Sector:'Capital Goods',industry:'Industrial Machinery/Components'},
{Symbol:'KDP',Name:'Keurig Dr Pepper Inc.',Price:27.16,Sector:'Consumer Non-Durables',industry:'Beverages (Production/Distribution)'},
{Symbol:'NGG',Name:'National Grid Transco, PLC',Price:54.01,Sector:'Public Utilities',industry:'Natural Gas Distribution'},
{Symbol:'GM',Name:'General Motors Company',Price:25.98,Sector:'Capital Goods',industry:'Auto Manufacturing'},
{Symbol:'CNC',Name:'Centene Corporation',Price:64.84,Sector:'Health Care',industry:'Medical Specialities'},
{Symbol:'SE',Name:'Sea Limited',Price:79,Sector:'Consumer Services',industry:'Other Consumer Services'},
{Symbol:'DLR',Name:'Digital Realty Trust, Inc.',Price:135.81,Sector:'Consumer Services',industry:'Real Estate Investment Trusts'},
{Symbol:'GIS',Name:'General Mills, Inc.',Price:59.96,Sector:'Consumer Non-Durables',industry:'Packaged Foods'},
{Symbol:'SRE',Name:'Sempra Energy',Price:123.81,Sector:'Public Utilities',industry:'Natural Gas Distribution'},
{Symbol:'SMFG',Name:'Sumitomo Mitsui Financial Group Inc',Price:5.28,Sector:'Finance',industry:'Commercial Banks'},
{Symbol:'HCA',Name:'HCA Healthcare, Inc.',Price:106.69,Sector:'Health Care',industry:'Hospital/Nursing Management'},
{Symbol:'WMT',Name:'Walmart Inc.',Price:124.33,Sector:'Consumer Services',industry:'Department/Specialty Retail Stores'},
{Symbol:'SQ',Name:'Square, Inc.',Price:81.49,Sector:'Technology',industry:'Computer Software: Prepackaged Software'},
{Symbol:'WBK',Name:'Westpac Banking Corporation',Price:9.94,Sector:'Finance',industry:'Commercial Banks'},
{Symbol:'LVS',Name:'Las Vegas Sands Corp.',Price:46.9,Sector:'Consumer Services',industry:'Hotels/Resorts'},
{Symbol:'DD',Name:'DuPont de Nemours, Inc.',Price:48.69,Sector:'Basic Industries',industry:'Major Chemicals'},
{Symbol:'SPOT',Name:'Spotify Technology S.A.',Price:190.17,Sector:'Consumer Services',industry:'Broadcasting'},
{Symbol:'BCE',Name:'BCE, Inc.',Price:39.07,Sector:'Public Utilities',industry:'Telecommunications Equipment'},
{Symbol:'UBS',Name:'UBS AG',Price:9.82,Sector:'Finance',industry:'Major Banks'},
{Symbol:'KMI',Name:'Kinder Morgan, Inc.',Price:15.41,Sector:'Public Utilities',industry:'Natural Gas Distribution'},
{Symbol:'SAN',Name:'Banco Santander, S.A.',Price:2.08,Sector:'Finance',industry:'Commercial Banks'},
{Symbol:'ABEV',Name:'Ambev S.A.',Price:2.14,Sector:'Consumer Non-Durables',industry:'Beverages (Production/Distribution)'},
{Symbol:'BSBR',Name:'Banco Santander Brasil SA',Price:4.5,Sector:'Finance',industry:'Commercial Banks'},
{Symbol:'PSX',Name:'Phillips 66',Price:76.46,Sector:'Energy',industry:'Integrated oil Companies'},
{Symbol:'EMR',Name:'Emerson Electric Company',Price:55.87,Sector:'Energy',industry:'Consumer Electronics/Appliances'},
{Symbol:'STZ',Name:'Constellation Brands Inc',Price:172.31,Sector:'Consumer Non-Durables',industry:'Beverages (Production/Distribution)'},
{Symbol:'CP',Name:'Canadian Pacific Railway Limited',Price:241.13,Sector:'Transportation',industry:'Railroads'},
{Symbol:'TRI',Name:'Thomson Reuters Corp',Price:66.24,Sector:'Consumer Services',industry:'Publishing'},
{Symbol:'PSA',Name:'Public Storage',Price:186.47,Sector:'Consumer Services',industry:'Real Estate Investment Trusts'},
{Symbol:'E',Name:'ENI S.p.A.',Price:18.03,Sector:'Energy',industry:'Oil & Gas Production'},
{Symbol:'DELL',Name:'Dell Technologies Inc.',Price:43.07,Sector:'Technology',industry:'Computer Manufacturing'},
{Symbol:'PUK',Name:'Prudential Public Limited Company',Price:24.26,Sector:'Finance',industry:'Life Insurance'},
{Symbol:'TAL',Name:'TAL Education Group',Price:53.3,Sector:'Consumer Services',industry:'Other Consumer Services'},
{Symbol:'ETN',Name:'Eaton Corporation, PLC',Price:78.67,Sector:'Technology',industry:'Industrial Machinery/Components'},
{Symbol:'FDX',Name:'FedEx Corporation',Price:117,Sector:'Transportation',industry:'Air Freight/Delivery Services'},
{Symbol:'BK',Name:'The Bank Of New York Mellon Corporation ',Price:34.5,Sector:'Finance',industry:'Major Banks'},
{Symbol:'VEEV',Name:'Veeva Systems Inc.',Price:202.96,Sector:'Technology',industry:'Computer Software: Prepackaged Software'},
{Symbol:'EOG',Name:'EOG Resources, Inc.',Price:52.28,Sector:'Energy',industry:'Oil & Gas Production'},
{Symbol:'MET',Name:'MetLife, Inc.',Price:33.34,Sector:'Finance',industry:'Life Insurance'},
{Symbol:'EQC',Name:'Equity Commonwealth',Price:32.84,Sector:'Consumer Services',industry:'Real Estate Investment Trusts'},
{Symbol:'WES',Name:'Western Midstream Partners, LP',Price:8.98,Sector:'Public Utilities',industry:'Natural Gas Distribution'},
{Symbol:'BSMX',Name:'Banco Santander Mexico, S.A., Institucion de Ban',Price:2.93,Sector:'Finance',industry:'Commercial Banks'},
{Symbol:'LEG',Name:'Leggett & Platt, Incorporated',Price:29.99,Sector:'Consumer Durables',industry:'Home Furnishings'},
{Symbol:'FSLY',Name:'Fastly, Inc.',Price:41.08,Sector:'Technology',industry:'Computer Software: Prepackaged Software'},
{Symbol:'PSN',Name:'Parsons Corporation',Price:39.35,Sector:'Technology',industry:'EDP Services'},
{Symbol:'SNDR',Name:'Schneider National, Inc.',Price:22.33,Sector:'Transportation',industry:'Trucking Freight/Courier Services'},
{Symbol:'VRT',Name:'Vertiv Holdings, LLC',Price:12.07,Sector:'Capital Goods',industry:'Industrial Machinery/Components'},
{Symbol:'CCJ',Name:'Cameco Corporation',Price:9.95,Sector:'Basic Industries',industry:'Precious Metals'},
{Symbol:'EQM',Name:'EQM Midstream Partners, LP',Price:18.99,Sector:'Public Utilities',industry:'Natural Gas Distribution'},
{Symbol:'DXC',Name:'DXC Technology Company',Price:15.48,Sector:'Technology',industry:'EDP Services'},
{Symbol:'TTM',Name:'Tata Motors Ltd',Price:5.46,Sector:'Capital Goods',industry:'Auto Manufacturing'},
{Symbol:'USFD',Name:'US Foods Holding Corp.',Price:17.81,Sector:'Consumer Non-Durables',industry:'Food Distributors'},
{Symbol:'HLI',Name:'Houlihan Lokey, Inc.',Price:59.83,Sector:'Finance',industry:'Investment Managers'},
{Symbol:'ALK',Name:'Alaska Air Group, Inc.',Price:31.02,Sector:'Transportation',industry:'Air Freight/Delivery Services'},
{Symbol:'AGCO',Name:'AGCO Corporation',Price:51.84,Sector:'Capital Goods',industry:'Industrial Machinery/Components'},
{Symbol:'CW',Name:'Curtiss-Wright Corporation',Price:92.57,Sector:'Technology',industry:'Industrial Machinery/Components'},
{Symbol:'TPR',Name:'Tapestry, Inc.',Price:13.98,Sector:'Consumer Non-Durables',industry:'Apparel'},
{Symbol:'PE',Name:'Parsley Energy, Inc.',Price:9.32,Sector:'Energy',industry:'Oil & Gas Production'},
{Symbol:'ASH',Name:'Ashland Global Holdings Inc.',Price:63.48,Sector:'Consumer Durables',industry:'Specialty Chemicals'},
{Symbol:'HUN',Name:'Huntsman Corporation',Price:17.39,Sector:'Basic Industries',industry:'Major Chemicals'},
{Symbol:'JBGS',Name:'JBG SMITH Properties',Price:28.71,Sector:'Consumer Services',industry:'Real Estate Investment Trusts'},
{Symbol:'POR',Name:'Portland General Electric Company',Price:42.95,Sector:'Public Utilities',industry:'Electric Utilities: Central'},
{Symbol:'SERV',Name:'ServiceMaster Global Holdings, Inc.',Price:29.13,Sector:'Consumer Services',industry:'Other Consumer Services'},
{Symbol:'NEWR',Name:'New Relic, Inc.',Price:63.81,Sector:'Technology',industry:'Computer Software: Prepackaged Software'},
{Symbol:'RH',Name:'RH',Price:198.15,Sector:'Consumer Services',industry:'Other Specialty Stores'},
{Symbol:'BKH',Name:'Black Hills Corporation',Price:59.03,Sector:'Public Utilities',industry:'Electric Utilities: Central'},
{Symbol:'UAA',Name:'Under Armour, Inc.',Price:8.34,Sector:'Consumer Non-Durables',industry:'Apparel'},
{Symbol:'JHG',Name:'Janus Henderson Group plc',Price:20.42,Sector:'Finance',industry:'Investment Managers'},
{Symbol:'NEA',Name:'Nuveen AMT-Free Quality Municipal Income Fund',Price:13.58,Sector:'n/a',industry:'n/a'},
{Symbol:'STAG',Name:'Stag Industrial, Inc.',Price:25.36,Sector:'Consumer Services',industry:'Real Estate Investment Trusts'},
{Symbol:'QTS',Name:'QTS Realty Trust, Inc.',Price:62.22,Sector:'Consumer Services',industry:'Real Estate Investment Trusts'},
{Symbol:'CLGX',Name:'CoreLogic, Inc.',Price:47.19,Sector:'Technology',industry:'EDP Services'},
{Symbol:'AER',Name:'Aercap Holdings N.V.',Price:28.8,Sector:'Technology',industry:'Diversified Commercial Services'},
{Symbol:'HOG',Name:'Harley-Davidson, Inc.',Price:24.38,Sector:'Consumer Non-Durables',industry:'Motor Vehicles'},
{Symbol:'MDLA',Name:'Medallia, Inc.',Price:26.97,Sector:'Technology',industry:'Computer Software: Programming, Data Processing'},
{Symbol:'BAK',Name:'Braskem S.A.',Price:9.34,Sector:'Basic Industries',industry:'Major Chemicals'},
{Symbol:'ENV',Name:'Envestnet, Inc',Price:69.47,Sector:'Miscellaneous',industry:'Business Services'},
{Symbol:'GPK',Name:'Graphic Packaging Holding Company',Price:13.32,Sector:'Consumer Durables',industry:'Containers/Packaging'},
{Symbol:'THG',Name:'The Hanover Insurance Group, Inc.',Price:97.53,Sector:'Finance',industry:'Property-Casualty Insurers'},
{Symbol:'CAE',Name:'CAE Inc',Price:13.56,Sector:'Miscellaneous',industry:'Industrial Machinery/Components'},
{Symbol:'VAC',Name:'Marriott Vacations Worldwide Corporation',Price:90,Sector:'Finance',industry:'Real Estate'},
{Symbol:'STWD',Name:'STARWOOD PROPERTY TRUST, INC.',Price:13.07,Sector:'Consumer Services',industry:'Real Estate Investment Trusts'},
{Symbol:'BLD',Name:'TopBuild Corp.',Price:110.44,Sector:'Basic Industries',industry:'Engineering & Construction'},
{Symbol:'SR',Name:'Spire Inc.',Price:71.6,Sector:'Public Utilities',industry:'Oil/Gas Transmission'},
{Symbol:'TOL',Name:'Toll Brothers, Inc.',Price:28.99,Sector:'Capital Goods',industry:'Homebuilding'},
{Symbol:'MSM',Name:'MSC Industrial Direct Company, Inc.',Price:65.37,Sector:'Capital Goods',industry:'Industrial Machinery/Components'},
{Symbol:'NFG',Name:'National Fuel Gas Company',Price:41.91,Sector:'Public Utilities',industry:'Oil/Gas Transmission'},
{Symbol:'XRX',Name:'Xerox Holdings Corporation',Price:16.98,Sector:'Technology',industry:'Computer peripheral equipment'},
{Symbol:'PRSP',Name:'Perspecta Inc.',Price:22.17,Sector:'Technology',industry:'EDP Services'},
{Symbol:'GGB',Name:'Gerdau S.A.',Price:2.1,Sector:'Capital Goods',industry:'Steel/Iron Ore'},
{Symbol:'HIW',Name:'Highwoods Properties, Inc.',Price:34.38,Sector:'Consumer Services',industry:'Real Estate Investment Trusts'},
{Symbol:'DAR',Name:'Darling Ingredients Inc.',Price:22.01,Sector:'Consumer Non-Durables',industry:'Packaged Foods'},
{Symbol:'JEF',Name:'Jefferies Financial Group Inc.',Price:13.25,Sector:'Finance',industry:'Investment Bankers/Brokers/Service'},
{Symbol:'NCLH',Name:'Norwegian Cruise Line Holdings Ltd.',Price:13.9,Sector:'Consumer Services',industry:'Marine Transportation'},
{Symbol:'CRI',Name:'Carter&#39;s, Inc.',Price:81.52,Sector:'Consumer Non-Durables',industry:'Apparel'},
{Symbol:'ORA',Name:'Ormat Technologies, Inc.',Price:68.89,Sector:'Public Utilities',industry:'Electric Utilities: Central'},
{Symbol:'EQT',Name:'EQT Corporation',Price:13.74,Sector:'Energy',industry:'Oil & Gas Production'},
{Symbol:'EME',Name:'EMCOR Group, Inc.',Price:62.06,Sector:'Capital Goods',industry:'Engineering & Construction'},
{Symbol:'AWI',Name:'Armstrong World Industries Inc',Price:71.31,Sector:'Consumer Non-Durables',industry:'Plastic Products'},
{Symbol:'RLI',Name:'RLI Corp.',Price:77.61,Sector:'Finance',industry:'Property-Casualty Insurers'},
{Symbol:'NIO',Name:'NIO Inc.',Price:3.27,Sector:'Capital Goods',industry:'Auto Manufacturing'},
{Symbol:'AN',Name:'AutoNation, Inc.',Price:39.79,Sector:'Consumer Durables',industry:'Automotive Aftermarket'},
{Symbol:'WWE',Name:'World Wrestling Entertainment, Inc.',Price:44.51,Sector:'Consumer Services',industry:'Movies/Entertainment'},
{Symbol:'TEO',Name:'Telecom Argentina Stet - France Telecom S.A.',Price:7.99,Sector:'Public Utilities',industry:'Telecommunications Equipment'},
{Symbol:'GRA',Name:'W.R. Grace & Co.',Price:51.97,Sector:'Basic Industries',industry:'Major Chemicals'},
{Symbol:'BHVN',Name:'Biohaven Pharmaceutical Holding Company Ltd.',Price:58.38,Sector:'Health Care',industry:'Major Pharmaceuticals'},
{Symbol:'PAC',Name:'Grupo Aeroportuario Del Pacifico, S.A. de C.V.',Price:61.05,Sector:'Transportation',industry:'Aerospace'}
]

var table = document.getElementById("mytable");
let data = Object.keys(obj[0]);


function tableHead(table, data) {
	let thead = table.createTHead();
	let row = thead.insertRow();
	for (let key of data){
		let th = document.createElement("th");
		let text = document.createTextNode(key);
		th.appendChild(text);
		row.appendChild(th);
	}
}


function genTable(table, obj) {
	for (let element of obj) {
		let row = table.insertRow();
		for (key in element) {
			let cell = row.insertCell();
			let text = document.createTextNode(element[key]);
			cell.appendChild(text);
		}
	}
}

tableHead(table, data);
genTable(table, obj);

